apiVersion: v1
deprecated: false
description: K8s API service to enable api access to outside of the cluster
name: k8s-api
version: 0.0.2
appVersion: 0.0.1
home: https://github.com/argeualcantara/k8s-api-service
sources:
  - https://github.com/argeualcantara/k8s-api-service