apiVersion: v1
kind: Service
metadata:
  name: {{ template "k8s-api.fullname" . }}
  labels:
    app: "{{ template "k8s-api.name" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: "{{ template "k8s-api.name" . }}"
    release: "{{ .Release.Name }}"